hologram:
- ''
history:
  format:
    name: '&fНик: &b{player}'
    lore:
    - ''
    - ' &fДата открытия: &c{date}'
    - ' &fВремя открытия: &c{time}'
    - ' &fВыигрыш: {prize}'
    - ''
  prizes:
  - FlamesYT;§f§dСупер-Игрок§f;10.10.2020;06:06:11
cases:
  donate:
    open-message:
    - ''
    - '  &fИгрок &a{player} &fоткрывает &bДонат Кейс&f на &c/warp case'
    - '  &fИспытай удачу и ты, купив кейсы на сайте &aMineLegacy.ru'
    - ''
    group-levels:
      enable: true
      levels:
        default: 0
        suser: 1
        creative: 2
        admin: 3
        lord: 4
        gladmin: 5
        sozd: 6
        osnov: 7
        glavar: 8
        sovlad: 9
        vlast: 10
    animation-settings:
      rotate-sound: UI_BUTTON_CLICK
      end-sound: BLOCK_CHEST_CLOSE
      radius: 1.25
      use-frostlord: true
      rotate-time: 3
      items-speed: 11.5
      particles-speed: 8
    items:
      suser:
        type: GROUP
        id: 397:3;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGNlZTNhZWFkZDY4YjI0N2ZkZmUzZWE3YmMwMDhkMTJmZDk3YWMxNWVkMTViZjc0Njg1NDNhMDY2ODAifX19
        group: suser
        group-command: pex user {player} group set {group}
        title: '&8[&dСупер-игрок&8]'
        commands:
        - tm;&aПоздравляем!;&fВы выбили &8[&dСупер-игрок&8]
        chance: 30
      creative:
        id: 397:3;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzMxYjE2MTc3MGYwMjAyMzdiNGFhMWU5MjhjNTQ4MGM4YjM2Y2JmZTNhNmFhYjllMjJlNTU3YzFkOTEwIn19fQ==
        type: GROUP
        group: creative
        group-command: pex user {player} group set {group}
        title: '&8[&aКреатив&8]'
        commands:
        - tm;&aПоздравляем!;&fВы выбили &8[&aКреатив&8]
        chance: 25
      admin:
        id: 397:3;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWIzMzQ4YTYxY2ZmYzc5ZWI0MmQ4NDlkMzc4MjI5NDMyYWE4MWQxOTg1NmIyNWZlYWFjNzUzODQ4NzEzN2E1In19fQ==
        type: GROUP
        group: admin
        group-command: pex user {player} group set {group}
        title: '&8[&cАдмин&8]'
        commands:
        - bc;&r
        - bc;&f  Игрок &c{player} &fвыиграл &8[&cАдмин&8] &fв донат кейсе
        - bc;&f  Хочешь круче? &fТогда купи кейс на сайте » &cMineLegacy.ru
        - bc;&r
        - tm;&aПоздравляем!;&fВы выбили &8[&cАдмин&8]
        chance: 21
      lord:
        id: 397:3;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjNkNWU0M2RlNWQ0MTc3YzRiYWYyZjQ0MTYxNTU0NDczYTNiMGJlNTQzMDk5OGI1ZmNkODI2YWY5NDNhZmUzIn19fQ==
        type: GROUP
        group: lord
        group-command: pex user {player} group set {group}
        title: '&8[&3Лорд&8]'
        commands:
        - bc;&r
        - bc;&f  Игрок &c{player} &fвыиграл &8[&3Лорд&8] &fв донат кейсе
        - bc;&f  Хочешь круче? &fТогда купи кейс на сайте » &cMineLegacy.ru
        - bc;&r
        - tm;&aПоздравляем!;&fВы выбили &8[&3Лорд&8]
        chance: 18
      gladmin:
        id: 397:3;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWRhZjY1NzcxZWZkNWQzMDQ3ZDRlZTQ2MDU0YzRlN2MzNzhkYzk2MWQ4ZjJiZTkzZDEzYTlkZDk1NjhlIn19fQ==
        type: GROUP
        group: gladmin
        group-command: pex user {player} group set {group}
        title: '&8[&9Гл.Админ&8]'
        commands:
        - bc;&r
        - bc;&f  Игрок &c{player} &fвыиграл &8[&9Гл.Админ&8] &fв донат кейсе
        - bc;&f  Хочешь круче? &fТогда купи кейс на сайте » &cMineLegacy.ru
        - bc;&r
        - tm;&aПоздравляем!;&fВы выбили &8[&9Гл.Админ&8]
        chance: 10
      sozd:
        id: 397:3;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmJhOGQ0YzM0MDgzNDY4MjYxMjY5MmMwNGJkYzUzMjk1MDI0YzQ4ZjM0MjI2ZTcyMTgyY2NkOWRlYzI1OTIifX19
        type: GROUP
        group: sozd
        group-command: pex user {player} group set {group}
        title: '&8[&eСоздатель&8]'
        commands:
        - bc;&r
        - bc;&f  Игрок &c{player} &fвыиграл &8[&eСоздатель&8] &fв донат кейсе
        - bc;&f  Хочешь круче? &fТогда купи кейс на сайте » &cMineLegacy.ru
        - bc;&r
        - tm;&aПоздравляем!;&fВы выбили &8[&eСоздатель&8]
        chance: 7
      osnov:
        id: 397:3;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWE3MzZlYjFhN2NlNWE1ZjVkNWIxNjg5MzFmYTMxMzk2Mzg2YzE2MDU2OGI0MTk2NGJhODZjZGI5ZWQ2YmUifX19
        type: GROUP
        group: osnov
        group-command: pex user {player} group set {group}
        title: '&8[&bОснователь&8]'
        commands:
        - bc;&r
        - bc;&f  Игрок &c{player} &fвыиграл &8[&bОснователь&8] &fв донат кейсе
        - bc;&f  Хочешь круче? &fТогда купи кейс на сайте » &cMineLegacy.ru
        - bc;&r
        - tm;&aПоздравляем!;&fВы выбили &8[&bОснователь&8]
        chance: 5
      glavar:
        id: 397:3;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjU4MDdjYzRjM2I2OTU4YWVhNjE1NmU4NDUxOGQ5MWE0OWM1ZjMyOTcxZTZlYjI2OWEyM2EyNWEyNzE0NSJ9fX0=
        type: GROUP
        group: glavar
        group-command: pex user {player} group set {group}
        title: '&8[&5Главарь&8]'
        commands:
        - bc;&r
        - bc;&f  Игрок &c{player} &fвыиграл &8[&5Главарь&8] &fв донат кейсе
        - bc;&f  Хочешь круче? &fТогда купи кейс на сайте » &cMineLegacy.ru
        - bc;&r
        - tm;&aПоздравляем!;&fВы выбили &8[&5Главарь&8]
        chance: 3
      sovlad:
        id: 397:3;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjU4MDdjYzRjM2I2OTU4YWVhNjE1NmU4NDUxOGQ5MWE0OWM1ZjMyOTcxZTZlYjI2OWEyM2EyNWEyNzE0NSJ9fX0=
        type: GROUP
        group: sovlad
        group-command: pex user {player} group set {group}
        title: '&8[&6Совладелец&8]'
        commands:
        - bc;&r
        - bc;&f  Игрок &c{player} &fвыиграл &8[&6Совладелец&8] &fв донат кейсе
        - bc;&f  Хочешь круче? &fТогда купи кейс на сайте » &cMineLegacy.ru
        - bc;&r
        - tm;&aПоздравляем!;&fВы выбили &8[&6Совладелец&8]
        chance: 2
      vlast:
        id: 397:3;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjU4MDdjYzRjM2I2OTU4YWVhNjE1NmU4NDUxOGQ5MWE0OWM1ZjMyOTcxZTZlYjI2OWEyM2EyNWEyNzE0NSJ9fX0=
        type: GROUP
        group: vlast
        group-command: pex user {player} group set {group}
        title: '&c[&4Властелин&c]'
        commands:
        - bc;&r
        - bc;&f  Игрок &c{player} &fвыиграл &c[&4Властелин&c] &fв донат кейсе
        - bc;&f  Покупка кейса производится на сайте » &cMineLegacy.ru
        - bc;&r
        - tm;&aПоздравляем!;&fВы выбили &c[&4Властелин&c]
        chance: 1
gui:
  rows: 6
  title: '&8Кейсы ► &4&lMineLegacy.ru'
  case-items:
    donate:
      id: 397:3;MHF_Present1
      slot: 31
      name: '&b&lКейс с донатом'
      lore:
        - '&a&l[!] &d&lБЫЛИ ПОВЫШЕНЫ ШАНСЫ! 100% ОКУП! &a&l[!]'
        - ''
        - '&a> &fКлючей от кейса&8: &c&l{keys}'
        - '&a> &fМожет выпасть от &a&lСупер-Игрока &fдо &c&lВластелина'
        - '&a> &f&lНажмите, чтобы открыть кейс'
        - ''
        - '&61 &fключ &7/ &e25 &fрублей'
        - '&63 &fключа &7/ &e75 &fрублей'
        - '&65 &fключей &7/ &e125 &fрублей'
        - '&610 &fключей &7/ &e175 &fрублей'
        - '&620 &fключей &7/ &e299 &fрублей'
        - '&630 &fключей &7/ &e499 &fрублей'
        - ''
        - '&4&lВНИМАНИЕ!!! &bПри открытии кейса у Вас'
        - '&bостается последняя выпавшая привилегия,'
        - '&bдаже если вам не повезло, и она дешевле'
        - ''
        - '&c> &fКупить можно на сайте&8:'
        - '&a&l&nMineLegacy.ru'
  default-items:
    info:
      slot: 4
      id: 340
      name: '&6Информация'
      lore:
        - ''
        - Покупка всех кейсов только на сайте &c&lMineLegacy.ru
        - Чтобы открыть кейс, нажмите по нему в этом меню
        - ''
        - '&fВнизу этого меню представлена &cистория выигрышей &f-'
        - '&fпризы, которые &cвыбивают &fигроки.'
        - ''
      amount: 1
    glass1:
      slot: 0
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass2:
      slot: 1
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass3:
      slot: 2
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass4:
      slot: 3
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass5:
      slot: 5
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass6:
      slot: 6
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass7:
      slot: 7
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass8:
      slot: 8
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass9:
      slot: 9
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass10:
      slot: 12
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass11:
      slot: 13
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass12:
      slot: 14
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass13:
      slot: 17
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass14:
      slot: 18
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass15:
      slot: 26
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass16:
      slot: 27
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass17:
      slot: 35
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass18:
      slot: 36
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
    glass19:
      slot: 44
      id: '160:14'
      name: ''
      lore:
        - ''
      amount: 1
case-locations:
- world;263;80;197;x
MESSAGES:
  NO_PERMISSIONS: '&f[&ci&f] У вас недостаточно прав!'
  HELP:
    - '&fКейсы.&f Помощь |'
    - ''
    - Выдать кейсы игроку - &a/dc givekey [ник] [название_кейса] [количество]
    - Установить кейсы игроку - &a/dc set [ник] [название_кейса] [количество]
    - Отнять кейсы у игрока - &a/dc delete [ник] [название_кейса] [количество]
    - Установить кейс - &a/dc setcase [направление x или z]
    - Обновить конфиг - &a/dc reload
    - ''
  NOT_NUMERIC: '&f[&ci&f] Вы неправильно ввели число'
  COMMAND_GIVE_USE: '&f[&ci&f] Вы неправильно ввели команду, выдать кейсы игроку - &a&l/dc givekey [ник] [название_кейса] [количество]'
  COMMAND_SET_USE: '&f[&ci&f] Вы неправильно ввели команду, установить кейсы игроку - &a&l/dc set [ник] [название_кейса] [количество]'
  COMMAND_DELETE_USE: '&f[&ci&f] Вы неправильно ввели команду, отнять кейсы у игрока - &a&l/dc delete [ник] [название_кейса] [количество]'
  COMMAND_SETCASE_USE: '&f[&ci&f] Вы неправильно ввели команду, установить кейс - &a&l/dc setcase [направление x или z]'
  COMMAND_GIVE_SUCCESS: '&f[&ci&f] Вы выдали игроку &a&l{player}&f &c&l{amount} {case}&f
    кейсов'
  COMMAND_SET_SUCCESS: '&f[&ci&f] Вы установили игроку &a&l{player}&f &c&l{amount}
    {case}&f кейсов'
  COMMAND_DELETE_SUCCESS: '&f[&ci&f] Вы отняли у игрока &a&l{player}&f &c&l{amount}
    {case}&f кейсов'
  COMMAND_SETCASE_SUCCESS: '&f[&ci&f] Вы успешно установили кейс по направлению вращения
    &c&l{direction}'
  CASE_NOT_LOADED: '&f[&ci&f] Непредвиденная ошибка'
  CASE_IS_OPEN: '&f[&ci&f] Кейс &aоткрывает &fдругой игрок. Пожалуйста, подождите.'
  NO_CASES: '&f[&ci&f] У вас &cнет &fкейсов этого типа. Купите кейсы на сайте &a&lMineLegacy.ru'
  COMMAND_SETCASE_SUCESS: '&f[&ci&f] Вы успешно установили кейс по направлению вращения
    &c&l{direction}'
